/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard/users'
import { Route as AuthenticatedDashboardTemplatesRouteImport } from './routes/_authenticated/dashboard/templates'
import { Route as AuthenticatedDashboardSmtpProfilesRouteImport } from './routes/_authenticated/dashboard/smtp-profiles'
import { Route as AuthenticatedDashboardShadowItRouteImport } from './routes/_authenticated/dashboard/shadow-it'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard/reports'
import { Route as AuthenticatedDashboardPlanRouteImport } from './routes/_authenticated/dashboard/plan'
import { Route as AuthenticatedDashboardPasswordsRouteImport } from './routes/_authenticated/dashboard/passwords'
import { Route as AuthenticatedDashboardOverviewRouteImport } from './routes/_authenticated/dashboard/overview'
import { Route as AuthenticatedDashboardOrganizationsRouteImport } from './routes/_authenticated/dashboard/organizations'
import { Route as AuthenticatedDashboardLandingPageTemplatesRouteImport } from './routes/_authenticated/dashboard/landing-page-templates'
import { Route as AuthenticatedDashboardGroupsRouteImport } from './routes/_authenticated/dashboard/groups'
import { Route as AuthenticatedDashboardGrcRouteImport } from './routes/_authenticated/dashboard/grc'
import { Route as AuthenticatedDashboardFormationsRouteImport } from './routes/_authenticated/dashboard/formations'
import { Route as AuthenticatedDashboardEncryptionRouteImport } from './routes/_authenticated/dashboard/encryption'
import { Route as AuthenticatedDashboardEmailSecurityRouteImport } from './routes/_authenticated/dashboard/email-security'
import { Route as AuthenticatedDashboardCampaignsRouteImport } from './routes/_authenticated/dashboard/campaigns'
import { Route as AuthenticatedDashboardUserIndexRouteImport } from './routes/_authenticated/dashboard/user/index'
import { Route as AuthenticatedDashboardOrganizationsIndexRouteImport } from './routes/_authenticated/dashboard/organizations/index'
import { Route as AuthenticatedDashboardFormationsIndexRouteImport } from './routes/_authenticated/dashboard/formations/index'
import { Route as AuthenticatedDashboardCampaignsIndexRouteImport } from './routes/_authenticated/dashboard/campaigns/index'
import { Route as AuthenticatedDashboardUserProfileRouteImport } from './routes/_authenticated/dashboard/user/profile'
import { Route as AuthenticatedDashboardUserFormationsRouteImport } from './routes/_authenticated/dashboard/user/formations'
import { Route as AuthenticatedDashboardUserFormationViewRouteImport } from './routes/_authenticated/dashboard/user/formation-view'
import { Route as AuthenticatedDashboardOrganizationsOrganizationIdRouteImport } from './routes/_authenticated/dashboard/organizations/$organizationId'
import { Route as AuthenticatedDashboardFormationsFormationEditRouteImport } from './routes/_authenticated/dashboard/formations/formation-edit'
import { Route as AuthenticatedDashboardFormationsCreateRouteImport } from './routes/_authenticated/dashboard/formations/create'
import { Route as AuthenticatedDashboardFormationsFormationIdRouteImport } from './routes/_authenticated/dashboard/formations/$formationId'
import { Route as AuthenticatedDashboardCampaignsCampaignIdRouteImport } from './routes/_authenticated/dashboard/campaigns/$campaignId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTemplatesRoute =
  AuthenticatedDashboardTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSmtpProfilesRoute =
  AuthenticatedDashboardSmtpProfilesRouteImport.update({
    id: '/smtp-profiles',
    path: '/smtp-profiles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShadowItRoute =
  AuthenticatedDashboardShadowItRouteImport.update({
    id: '/shadow-it',
    path: '/shadow-it',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPlanRoute =
  AuthenticatedDashboardPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPasswordsRoute =
  AuthenticatedDashboardPasswordsRouteImport.update({
    id: '/passwords',
    path: '/passwords',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOverviewRoute =
  AuthenticatedDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrganizationsRoute =
  AuthenticatedDashboardOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLandingPageTemplatesRoute =
  AuthenticatedDashboardLandingPageTemplatesRouteImport.update({
    id: '/landing-page-templates',
    path: '/landing-page-templates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGroupsRoute =
  AuthenticatedDashboardGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGrcRoute =
  AuthenticatedDashboardGrcRouteImport.update({
    id: '/grc',
    path: '/grc',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFormationsRoute =
  AuthenticatedDashboardFormationsRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEncryptionRoute =
  AuthenticatedDashboardEncryptionRouteImport.update({
    id: '/encryption',
    path: '/encryption',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEmailSecurityRoute =
  AuthenticatedDashboardEmailSecurityRouteImport.update({
    id: '/email-security',
    path: '/email-security',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCampaignsRoute =
  AuthenticatedDashboardCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUserIndexRoute =
  AuthenticatedDashboardUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrganizationsIndexRoute =
  AuthenticatedDashboardOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOrganizationsRoute,
  } as any)
const AuthenticatedDashboardFormationsIndexRoute =
  AuthenticatedDashboardFormationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardFormationsRoute,
  } as any)
const AuthenticatedDashboardCampaignsIndexRoute =
  AuthenticatedDashboardCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardCampaignsRoute,
  } as any)
const AuthenticatedDashboardUserProfileRoute =
  AuthenticatedDashboardUserProfileRouteImport.update({
    id: '/user/profile',
    path: '/user/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUserFormationsRoute =
  AuthenticatedDashboardUserFormationsRouteImport.update({
    id: '/user/formations',
    path: '/user/formations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUserFormationViewRoute =
  AuthenticatedDashboardUserFormationViewRouteImport.update({
    id: '/user/formation-view',
    path: '/user/formation-view',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrganizationsOrganizationIdRoute =
  AuthenticatedDashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AuthenticatedDashboardOrganizationsRoute,
  } as any)
const AuthenticatedDashboardFormationsFormationEditRoute =
  AuthenticatedDashboardFormationsFormationEditRouteImport.update({
    id: '/formation-edit',
    path: '/formation-edit',
    getParentRoute: () => AuthenticatedDashboardFormationsRoute,
  } as any)
const AuthenticatedDashboardFormationsCreateRoute =
  AuthenticatedDashboardFormationsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedDashboardFormationsRoute,
  } as any)
const AuthenticatedDashboardFormationsFormationIdRoute =
  AuthenticatedDashboardFormationsFormationIdRouteImport.update({
    id: '/$formationId',
    path: '/$formationId',
    getParentRoute: () => AuthenticatedDashboardFormationsRoute,
  } as any)
const AuthenticatedDashboardCampaignsCampaignIdRoute =
  AuthenticatedDashboardCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedDashboardCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/campaigns': typeof AuthenticatedDashboardCampaignsRouteWithChildren
  '/dashboard/email-security': typeof AuthenticatedDashboardEmailSecurityRoute
  '/dashboard/encryption': typeof AuthenticatedDashboardEncryptionRoute
  '/dashboard/formations': typeof AuthenticatedDashboardFormationsRouteWithChildren
  '/dashboard/grc': typeof AuthenticatedDashboardGrcRoute
  '/dashboard/groups': typeof AuthenticatedDashboardGroupsRoute
  '/dashboard/landing-page-templates': typeof AuthenticatedDashboardLandingPageTemplatesRoute
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRouteWithChildren
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/passwords': typeof AuthenticatedDashboardPasswordsRoute
  '/dashboard/plan': typeof AuthenticatedDashboardPlanRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shadow-it': typeof AuthenticatedDashboardShadowItRoute
  '/dashboard/smtp-profiles': typeof AuthenticatedDashboardSmtpProfilesRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof AuthenticatedDashboardCampaignsCampaignIdRoute
  '/dashboard/formations/$formationId': typeof AuthenticatedDashboardFormationsFormationIdRoute
  '/dashboard/formations/create': typeof AuthenticatedDashboardFormationsCreateRoute
  '/dashboard/formations/formation-edit': typeof AuthenticatedDashboardFormationsFormationEditRoute
  '/dashboard/organizations/$organizationId': typeof AuthenticatedDashboardOrganizationsOrganizationIdRoute
  '/dashboard/user/formation-view': typeof AuthenticatedDashboardUserFormationViewRoute
  '/dashboard/user/formations': typeof AuthenticatedDashboardUserFormationsRoute
  '/dashboard/user/profile': typeof AuthenticatedDashboardUserProfileRoute
  '/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/dashboard/formations/': typeof AuthenticatedDashboardFormationsIndexRoute
  '/dashboard/organizations/': typeof AuthenticatedDashboardOrganizationsIndexRoute
  '/dashboard/user/': typeof AuthenticatedDashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/email-security': typeof AuthenticatedDashboardEmailSecurityRoute
  '/dashboard/encryption': typeof AuthenticatedDashboardEncryptionRoute
  '/dashboard/grc': typeof AuthenticatedDashboardGrcRoute
  '/dashboard/groups': typeof AuthenticatedDashboardGroupsRoute
  '/dashboard/landing-page-templates': typeof AuthenticatedDashboardLandingPageTemplatesRoute
  '/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/dashboard/passwords': typeof AuthenticatedDashboardPasswordsRoute
  '/dashboard/plan': typeof AuthenticatedDashboardPlanRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/shadow-it': typeof AuthenticatedDashboardShadowItRoute
  '/dashboard/smtp-profiles': typeof AuthenticatedDashboardSmtpProfilesRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof AuthenticatedDashboardCampaignsCampaignIdRoute
  '/dashboard/formations/$formationId': typeof AuthenticatedDashboardFormationsFormationIdRoute
  '/dashboard/formations/create': typeof AuthenticatedDashboardFormationsCreateRoute
  '/dashboard/formations/formation-edit': typeof AuthenticatedDashboardFormationsFormationEditRoute
  '/dashboard/organizations/$organizationId': typeof AuthenticatedDashboardOrganizationsOrganizationIdRoute
  '/dashboard/user/formation-view': typeof AuthenticatedDashboardUserFormationViewRoute
  '/dashboard/user/formations': typeof AuthenticatedDashboardUserFormationsRoute
  '/dashboard/user/profile': typeof AuthenticatedDashboardUserProfileRoute
  '/dashboard/campaigns': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/dashboard/formations': typeof AuthenticatedDashboardFormationsIndexRoute
  '/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsIndexRoute
  '/dashboard/user': typeof AuthenticatedDashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/campaigns': typeof AuthenticatedDashboardCampaignsRouteWithChildren
  '/_authenticated/dashboard/email-security': typeof AuthenticatedDashboardEmailSecurityRoute
  '/_authenticated/dashboard/encryption': typeof AuthenticatedDashboardEncryptionRoute
  '/_authenticated/dashboard/formations': typeof AuthenticatedDashboardFormationsRouteWithChildren
  '/_authenticated/dashboard/grc': typeof AuthenticatedDashboardGrcRoute
  '/_authenticated/dashboard/groups': typeof AuthenticatedDashboardGroupsRoute
  '/_authenticated/dashboard/landing-page-templates': typeof AuthenticatedDashboardLandingPageTemplatesRoute
  '/_authenticated/dashboard/organizations': typeof AuthenticatedDashboardOrganizationsRouteWithChildren
  '/_authenticated/dashboard/overview': typeof AuthenticatedDashboardOverviewRoute
  '/_authenticated/dashboard/passwords': typeof AuthenticatedDashboardPasswordsRoute
  '/_authenticated/dashboard/plan': typeof AuthenticatedDashboardPlanRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/shadow-it': typeof AuthenticatedDashboardShadowItRoute
  '/_authenticated/dashboard/smtp-profiles': typeof AuthenticatedDashboardSmtpProfilesRoute
  '/_authenticated/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/campaigns/$campaignId': typeof AuthenticatedDashboardCampaignsCampaignIdRoute
  '/_authenticated/dashboard/formations/$formationId': typeof AuthenticatedDashboardFormationsFormationIdRoute
  '/_authenticated/dashboard/formations/create': typeof AuthenticatedDashboardFormationsCreateRoute
  '/_authenticated/dashboard/formations/formation-edit': typeof AuthenticatedDashboardFormationsFormationEditRoute
  '/_authenticated/dashboard/organizations/$organizationId': typeof AuthenticatedDashboardOrganizationsOrganizationIdRoute
  '/_authenticated/dashboard/user/formation-view': typeof AuthenticatedDashboardUserFormationViewRoute
  '/_authenticated/dashboard/user/formations': typeof AuthenticatedDashboardUserFormationsRoute
  '/_authenticated/dashboard/user/profile': typeof AuthenticatedDashboardUserProfileRoute
  '/_authenticated/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
  '/_authenticated/dashboard/formations/': typeof AuthenticatedDashboardFormationsIndexRoute
  '/_authenticated/dashboard/organizations/': typeof AuthenticatedDashboardOrganizationsIndexRoute
  '/_authenticated/dashboard/user/': typeof AuthenticatedDashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/dashboard/email-security'
    | '/dashboard/encryption'
    | '/dashboard/formations'
    | '/dashboard/grc'
    | '/dashboard/groups'
    | '/dashboard/landing-page-templates'
    | '/dashboard/organizations'
    | '/dashboard/overview'
    | '/dashboard/passwords'
    | '/dashboard/plan'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/shadow-it'
    | '/dashboard/smtp-profiles'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/formations/$formationId'
    | '/dashboard/formations/create'
    | '/dashboard/formations/formation-edit'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/user/formation-view'
    | '/dashboard/user/formations'
    | '/dashboard/user/profile'
    | '/dashboard/campaigns/'
    | '/dashboard/formations/'
    | '/dashboard/organizations/'
    | '/dashboard/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/email-security'
    | '/dashboard/encryption'
    | '/dashboard/grc'
    | '/dashboard/groups'
    | '/dashboard/landing-page-templates'
    | '/dashboard/overview'
    | '/dashboard/passwords'
    | '/dashboard/plan'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/shadow-it'
    | '/dashboard/smtp-profiles'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/formations/$formationId'
    | '/dashboard/formations/create'
    | '/dashboard/formations/formation-edit'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/user/formation-view'
    | '/dashboard/user/formations'
    | '/dashboard/user/profile'
    | '/dashboard/campaigns'
    | '/dashboard/formations'
    | '/dashboard/organizations'
    | '/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/campaigns'
    | '/_authenticated/dashboard/email-security'
    | '/_authenticated/dashboard/encryption'
    | '/_authenticated/dashboard/formations'
    | '/_authenticated/dashboard/grc'
    | '/_authenticated/dashboard/groups'
    | '/_authenticated/dashboard/landing-page-templates'
    | '/_authenticated/dashboard/organizations'
    | '/_authenticated/dashboard/overview'
    | '/_authenticated/dashboard/passwords'
    | '/_authenticated/dashboard/plan'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/shadow-it'
    | '/_authenticated/dashboard/smtp-profiles'
    | '/_authenticated/dashboard/templates'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/campaigns/$campaignId'
    | '/_authenticated/dashboard/formations/$formationId'
    | '/_authenticated/dashboard/formations/create'
    | '/_authenticated/dashboard/formations/formation-edit'
    | '/_authenticated/dashboard/organizations/$organizationId'
    | '/_authenticated/dashboard/user/formation-view'
    | '/_authenticated/dashboard/user/formations'
    | '/_authenticated/dashboard/user/profile'
    | '/_authenticated/dashboard/campaigns/'
    | '/_authenticated/dashboard/formations/'
    | '/_authenticated/dashboard/organizations/'
    | '/_authenticated/dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/templates': {
      id: '/_authenticated/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof AuthenticatedDashboardTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/smtp-profiles': {
      id: '/_authenticated/dashboard/smtp-profiles'
      path: '/smtp-profiles'
      fullPath: '/dashboard/smtp-profiles'
      preLoaderRoute: typeof AuthenticatedDashboardSmtpProfilesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shadow-it': {
      id: '/_authenticated/dashboard/shadow-it'
      path: '/shadow-it'
      fullPath: '/dashboard/shadow-it'
      preLoaderRoute: typeof AuthenticatedDashboardShadowItRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/plan': {
      id: '/_authenticated/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof AuthenticatedDashboardPlanRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/passwords': {
      id: '/_authenticated/dashboard/passwords'
      path: '/passwords'
      fullPath: '/dashboard/passwords'
      preLoaderRoute: typeof AuthenticatedDashboardPasswordsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/overview': {
      id: '/_authenticated/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedDashboardOverviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/organizations': {
      id: '/_authenticated/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/landing-page-templates': {
      id: '/_authenticated/dashboard/landing-page-templates'
      path: '/landing-page-templates'
      fullPath: '/dashboard/landing-page-templates'
      preLoaderRoute: typeof AuthenticatedDashboardLandingPageTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/groups': {
      id: '/_authenticated/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof AuthenticatedDashboardGroupsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/grc': {
      id: '/_authenticated/dashboard/grc'
      path: '/grc'
      fullPath: '/dashboard/grc'
      preLoaderRoute: typeof AuthenticatedDashboardGrcRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/formations': {
      id: '/_authenticated/dashboard/formations'
      path: '/formations'
      fullPath: '/dashboard/formations'
      preLoaderRoute: typeof AuthenticatedDashboardFormationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/encryption': {
      id: '/_authenticated/dashboard/encryption'
      path: '/encryption'
      fullPath: '/dashboard/encryption'
      preLoaderRoute: typeof AuthenticatedDashboardEncryptionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/email-security': {
      id: '/_authenticated/dashboard/email-security'
      path: '/email-security'
      fullPath: '/dashboard/email-security'
      preLoaderRoute: typeof AuthenticatedDashboardEmailSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/campaigns': {
      id: '/_authenticated/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/user/': {
      id: '/_authenticated/dashboard/user/'
      path: '/user'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof AuthenticatedDashboardUserIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/organizations/': {
      id: '/_authenticated/dashboard/organizations/'
      path: '/'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationsRoute
    }
    '/_authenticated/dashboard/formations/': {
      id: '/_authenticated/dashboard/formations/'
      path: '/'
      fullPath: '/dashboard/formations/'
      preLoaderRoute: typeof AuthenticatedDashboardFormationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardFormationsRoute
    }
    '/_authenticated/dashboard/campaigns/': {
      id: '/_authenticated/dashboard/campaigns/'
      path: '/'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardCampaignsRoute
    }
    '/_authenticated/dashboard/user/profile': {
      id: '/_authenticated/dashboard/user/profile'
      path: '/user/profile'
      fullPath: '/dashboard/user/profile'
      preLoaderRoute: typeof AuthenticatedDashboardUserProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/user/formations': {
      id: '/_authenticated/dashboard/user/formations'
      path: '/user/formations'
      fullPath: '/dashboard/user/formations'
      preLoaderRoute: typeof AuthenticatedDashboardUserFormationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/user/formation-view': {
      id: '/_authenticated/dashboard/user/formation-view'
      path: '/user/formation-view'
      fullPath: '/dashboard/user/formation-view'
      preLoaderRoute: typeof AuthenticatedDashboardUserFormationViewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/organizations/$organizationId': {
      id: '/_authenticated/dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/dashboard/organizations/$organizationId'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationsRoute
    }
    '/_authenticated/dashboard/formations/formation-edit': {
      id: '/_authenticated/dashboard/formations/formation-edit'
      path: '/formation-edit'
      fullPath: '/dashboard/formations/formation-edit'
      preLoaderRoute: typeof AuthenticatedDashboardFormationsFormationEditRouteImport
      parentRoute: typeof AuthenticatedDashboardFormationsRoute
    }
    '/_authenticated/dashboard/formations/create': {
      id: '/_authenticated/dashboard/formations/create'
      path: '/create'
      fullPath: '/dashboard/formations/create'
      preLoaderRoute: typeof AuthenticatedDashboardFormationsCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardFormationsRoute
    }
    '/_authenticated/dashboard/formations/$formationId': {
      id: '/_authenticated/dashboard/formations/$formationId'
      path: '/$formationId'
      fullPath: '/dashboard/formations/$formationId'
      preLoaderRoute: typeof AuthenticatedDashboardFormationsFormationIdRouteImport
      parentRoute: typeof AuthenticatedDashboardFormationsRoute
    }
    '/_authenticated/dashboard/campaigns/$campaignId': {
      id: '/_authenticated/dashboard/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCampaignsRoute
    }
  }
}

interface AuthenticatedDashboardCampaignsRouteChildren {
  AuthenticatedDashboardCampaignsCampaignIdRoute: typeof AuthenticatedDashboardCampaignsCampaignIdRoute
  AuthenticatedDashboardCampaignsIndexRoute: typeof AuthenticatedDashboardCampaignsIndexRoute
}

const AuthenticatedDashboardCampaignsRouteChildren: AuthenticatedDashboardCampaignsRouteChildren =
  {
    AuthenticatedDashboardCampaignsCampaignIdRoute:
      AuthenticatedDashboardCampaignsCampaignIdRoute,
    AuthenticatedDashboardCampaignsIndexRoute:
      AuthenticatedDashboardCampaignsIndexRoute,
  }

const AuthenticatedDashboardCampaignsRouteWithChildren =
  AuthenticatedDashboardCampaignsRoute._addFileChildren(
    AuthenticatedDashboardCampaignsRouteChildren,
  )

interface AuthenticatedDashboardFormationsRouteChildren {
  AuthenticatedDashboardFormationsFormationIdRoute: typeof AuthenticatedDashboardFormationsFormationIdRoute
  AuthenticatedDashboardFormationsCreateRoute: typeof AuthenticatedDashboardFormationsCreateRoute
  AuthenticatedDashboardFormationsFormationEditRoute: typeof AuthenticatedDashboardFormationsFormationEditRoute
  AuthenticatedDashboardFormationsIndexRoute: typeof AuthenticatedDashboardFormationsIndexRoute
}

const AuthenticatedDashboardFormationsRouteChildren: AuthenticatedDashboardFormationsRouteChildren =
  {
    AuthenticatedDashboardFormationsFormationIdRoute:
      AuthenticatedDashboardFormationsFormationIdRoute,
    AuthenticatedDashboardFormationsCreateRoute:
      AuthenticatedDashboardFormationsCreateRoute,
    AuthenticatedDashboardFormationsFormationEditRoute:
      AuthenticatedDashboardFormationsFormationEditRoute,
    AuthenticatedDashboardFormationsIndexRoute:
      AuthenticatedDashboardFormationsIndexRoute,
  }

const AuthenticatedDashboardFormationsRouteWithChildren =
  AuthenticatedDashboardFormationsRoute._addFileChildren(
    AuthenticatedDashboardFormationsRouteChildren,
  )

interface AuthenticatedDashboardOrganizationsRouteChildren {
  AuthenticatedDashboardOrganizationsOrganizationIdRoute: typeof AuthenticatedDashboardOrganizationsOrganizationIdRoute
  AuthenticatedDashboardOrganizationsIndexRoute: typeof AuthenticatedDashboardOrganizationsIndexRoute
}

const AuthenticatedDashboardOrganizationsRouteChildren: AuthenticatedDashboardOrganizationsRouteChildren =
  {
    AuthenticatedDashboardOrganizationsOrganizationIdRoute:
      AuthenticatedDashboardOrganizationsOrganizationIdRoute,
    AuthenticatedDashboardOrganizationsIndexRoute:
      AuthenticatedDashboardOrganizationsIndexRoute,
  }

const AuthenticatedDashboardOrganizationsRouteWithChildren =
  AuthenticatedDashboardOrganizationsRoute._addFileChildren(
    AuthenticatedDashboardOrganizationsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCampaignsRoute: typeof AuthenticatedDashboardCampaignsRouteWithChildren
  AuthenticatedDashboardEmailSecurityRoute: typeof AuthenticatedDashboardEmailSecurityRoute
  AuthenticatedDashboardEncryptionRoute: typeof AuthenticatedDashboardEncryptionRoute
  AuthenticatedDashboardFormationsRoute: typeof AuthenticatedDashboardFormationsRouteWithChildren
  AuthenticatedDashboardGrcRoute: typeof AuthenticatedDashboardGrcRoute
  AuthenticatedDashboardGroupsRoute: typeof AuthenticatedDashboardGroupsRoute
  AuthenticatedDashboardLandingPageTemplatesRoute: typeof AuthenticatedDashboardLandingPageTemplatesRoute
  AuthenticatedDashboardOrganizationsRoute: typeof AuthenticatedDashboardOrganizationsRouteWithChildren
  AuthenticatedDashboardOverviewRoute: typeof AuthenticatedDashboardOverviewRoute
  AuthenticatedDashboardPasswordsRoute: typeof AuthenticatedDashboardPasswordsRoute
  AuthenticatedDashboardPlanRoute: typeof AuthenticatedDashboardPlanRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardShadowItRoute: typeof AuthenticatedDashboardShadowItRoute
  AuthenticatedDashboardSmtpProfilesRoute: typeof AuthenticatedDashboardSmtpProfilesRoute
  AuthenticatedDashboardTemplatesRoute: typeof AuthenticatedDashboardTemplatesRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardUserFormationViewRoute: typeof AuthenticatedDashboardUserFormationViewRoute
  AuthenticatedDashboardUserFormationsRoute: typeof AuthenticatedDashboardUserFormationsRoute
  AuthenticatedDashboardUserProfileRoute: typeof AuthenticatedDashboardUserProfileRoute
  AuthenticatedDashboardUserIndexRoute: typeof AuthenticatedDashboardUserIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCampaignsRoute:
      AuthenticatedDashboardCampaignsRouteWithChildren,
    AuthenticatedDashboardEmailSecurityRoute:
      AuthenticatedDashboardEmailSecurityRoute,
    AuthenticatedDashboardEncryptionRoute:
      AuthenticatedDashboardEncryptionRoute,
    AuthenticatedDashboardFormationsRoute:
      AuthenticatedDashboardFormationsRouteWithChildren,
    AuthenticatedDashboardGrcRoute: AuthenticatedDashboardGrcRoute,
    AuthenticatedDashboardGroupsRoute: AuthenticatedDashboardGroupsRoute,
    AuthenticatedDashboardLandingPageTemplatesRoute:
      AuthenticatedDashboardLandingPageTemplatesRoute,
    AuthenticatedDashboardOrganizationsRoute:
      AuthenticatedDashboardOrganizationsRouteWithChildren,
    AuthenticatedDashboardOverviewRoute: AuthenticatedDashboardOverviewRoute,
    AuthenticatedDashboardPasswordsRoute: AuthenticatedDashboardPasswordsRoute,
    AuthenticatedDashboardPlanRoute: AuthenticatedDashboardPlanRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardShadowItRoute: AuthenticatedDashboardShadowItRoute,
    AuthenticatedDashboardSmtpProfilesRoute:
      AuthenticatedDashboardSmtpProfilesRoute,
    AuthenticatedDashboardTemplatesRoute: AuthenticatedDashboardTemplatesRoute,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardUserFormationViewRoute:
      AuthenticatedDashboardUserFormationViewRoute,
    AuthenticatedDashboardUserFormationsRoute:
      AuthenticatedDashboardUserFormationsRoute,
    AuthenticatedDashboardUserProfileRoute:
      AuthenticatedDashboardUserProfileRoute,
    AuthenticatedDashboardUserIndexRoute: AuthenticatedDashboardUserIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
